import {test,expect} from '@playwright/test';
const key='gonzo.friends.portfolio.v1';
async function mocks(page){await page.route('**/friends/api/**',async r=>{const u=new URL(r.request().url()),quotes={};for(const s of (u.searchParams.get('stocks')||'').split(',').filter(Boolean))quotes[s]={price:100,dailyPct:1,timestamp:Date.now()/1000,status:'connected',provider:'Test'};for(const c of (u.searchParams.get('crypto')||'').split(',').filter(Boolean))quotes[c.split(':')[0]]={price:100,dailyPct:1,timestamp:Date.now()/1000,status:'connected',provider:'Test'};await r.fulfill({json:u.pathname.endsWith('/news')?{news:[],newsStatus:'connected',fetchedAt:Date.now()/1000}:{schema:1,quotes,issues:[],fetchedAt:Date.now()/1000}});});}
test('friend mobile starts blank, adds holdings, shares mobile URL and keeps existing friend state',async({page})=>{
await page.setViewportSize({width:390,height:844});await mocks(page);await page.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedLink=text;}},configurable:true});});
await page.goto('/friends/mobile/');await expect(page.locator('#stockCount')).toHaveText('0');await expect(page.locator('#cryptoCount')).toHaveText('0');
await page.locator('#firstHolding').click();await page.locator('#assetSymbol').fill('AAPL');await page.locator('#assetQuantity').fill('2.5');await page.locator('#saveHolding').click();await expect(page.locator('#stockCount')).toHaveText('1');
await page.locator('#mobileMore summary').click();await page.locator('#shareDashboard').click();expect(await page.evaluate(()=>window.copiedLink)).toContain('/friends/mobile/');await expect(page.locator('#mobileMore')).not.toHaveAttribute('open','');
await page.goto('/friends/');await expect(page.locator('#stockCount')).toHaveText('1');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).holdings.stocks[0].quantity,key)).toBe(2.5);
});
for(const [width,height] of [[390,844],[360,800],[412,915],[320,568],[844,390]]){
test('friend mobile all holdings fit '+width+'x'+height,async({page})=>{
await page.setViewportSize({width,height});await mocks(page);await page.addInitScript(({key})=>{localStorage.setItem(key,JSON.stringify({holdings:{stocks:Array.from({length:24},(_,i)=>({symbol:'S'+i,quantity:20.5,cost:null})),crypto:Array.from({length:14},(_,i)=>({symbol:'C'+i,quantity:20.5,id:'bitcoin'})),metadata:{}},rules:[]}));},{key});await page.goto('/friends/mobile/');await expect(page.locator('#coverage')).toContainText('38/38');await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(requestAnimationFrame));
const result=await page.evaluate(()=>{const d=document.documentElement;const clipped=[...document.querySelectorAll('.holding b,.holding small')].filter(el=>el.getClientRects().length&&getComputedStyle(el).display!=='none').filter(el=>{const r=document.createRange();r.selectNodeContents(el);const a=r.getBoundingClientRect(),b=el.closest('.holding').getBoundingClientRect();return a.left<b.left-1||a.right>b.right+1||a.top<b.top-1||a.bottom>b.bottom+1;}).map(el=>el.textContent);return {w:d.scrollWidth,h:d.scrollHeight,clipped};});expect(result.w).toBeLessThanOrEqual(width);expect(result.h).toBeLessThanOrEqual(height);expect(result.clipped).toEqual([]);await expect(page.locator('#stocks .holding')).toHaveCount(24);await expect(page.locator('#cryptos .holding')).toHaveCount(14);
});}
